server:
  port: 8081
spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true