server:
  port: 8081
spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  mail:
    host: smtp.mail.ru
    port: 587
    username: *********
    password: *********
    protocol: smtp

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

notification:
  send-email-cron: "0 * * * * *"







