repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.19.0
    hooks:
      - id: gitleaks
        args: ["git", "--report-path=gitleaks-report.json"]
      - id: send-report
        name: Send Gitleaks Report
        entry: ./send_report.sh
        language: script
