server:
  port: 8085
spring:
  application:
    name: storage-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: trace
