server:
  port: 8885
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lesya899/configs.git
          username: ${USER_NAME}
          password: ${SERVER_CONFIG_PASSWORD}
          default-label: main
          search-paths: "{application}"
