server:
  port: 8885
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lesya899/configs.git
          username: ${USER_NAME:Lesya899}
          password: ${SERVER_CONFIG_PASSWORD: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}
          default-label: main
          search-paths: "{application}"
