server:
  port: 8885
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lesya899/configs.git
          username: Lesya899
          password: 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
          default-label: main
          search-paths: "{application}"
