name: Dependency Track Scan

on:
  push:
    branches:
      - main pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest steps:
      - name: Checkout code uses: actions/checkout@v2 - name: Set up JDK
        uses: actions/setup-java@v1 with:
          java-version: '21'  # Укажите нужную версию JDK - name: Build project
        run: |
          ./gradlew build  # Или используйте другую команду для сборки вашего проекта

      - name: Scan dependencies
        env:
          DEPENDENCY_TRACK_API_URL: ${{ secrets.DEPENDENCY_TRACK_API_URL }}
          DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
        run: |
          curl -X POST "$DEPENDENCY_TRACK_API_URL/api/v1/project/{projectId}/analysis" \
          -H "X-Api-Key: $DEPENDENCY_TRACK_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"projectId":"a2240a31-ae2e-485f-b624-9006b305a226","projectVersion":"1.0.0","projectName":"stores"}'
