name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Gitleaks
      run: gitleaks git --v --report-path gitleaks-report.json

    - name: Upload report to API
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d @gitleaks-report.json http://localhost:8080/api/report
         
