name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Gitleaks
      run: |
        git clone https://github.com/gitleaks/gitleaks.git
        cd gitleaks
        make build
        sudo mv gitleaks /usr/local/bin/

    - name: Run Gitleaks
      run: |
        gitleaks git --redact --exit-code=2 --report-format=json --report-path=gitleaks-report.json --log-level=error

    - name: Upload report to API
      run: |
       curl -X POST -f "file=@gitleaks-report.json" http://192.168.50.236:8080/api/report
        
