name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2      

    - name: Upload report to API
      run: |
        if [ -f gitleaks-report.json ]; then
          echo "Отчет найден, отправка на API..."
          curl -X POST -H "Content-Type: application/json" \
          -d @gitleaks-report.json http://localhost:8080/api/report
        else
          echo "Отчет gitleaks-report.json не найден."
          exit 1
        fi
         
