name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

    - name: Run Gitleaks
      run: |
        gitleaks git --redact -v --exit-code=2 --report-format=json --report-path=gitleaks-report.json --log-level=debug --log-opts=-1

    - name: Upload report to API
      run: |
        if [ -f gitleaks-report.json ]; then
          echo "Отчет найден, отправка на API..."
          curl -X POST -H "Content-Type: application/json" \
          -d @gitleaks-report.json http://localhost:8080/api/report
        else
          echo "gitleaks-report.json не найден."
          exit 1
        fi

         
